### ISSUE TITLE
Nav needs to be completed, or ready

### ISSUE THREAD

**Issue by cbadger44** [steventhomasmiller/National-School-of-Academic-Equitation#11]
I will start the implementation of the nav bar with a drop down. also create php pages for what pages we have in regards of the current information architecture. as it changes so will the pages, of course.

**Comment by cbadger44** [comment]
still working on nav. i will create sample pages to experiment with layout.

**Comment by steventhomasmiller** [comment]
That sounds good. I will work with fully implementing the sidebars.

**Comment by EllenTackett** [comment]
There are not any sidebars we removed them from the wireframes before the client presentation. Is there something else you are referencing?

Sent from my Sony Xperia® Z1ˢ on T-Mobile’s 4G LTE Network

---- steventhomasmiller wrote ----

**Comment by steventhomasmiller** [comment]
Just the ones on my local environment, which I'm using to test widget functionality ::-)

**Comment by cbadger44** [comment]
Got navigation menu to drop down. Just needs to be styled.
