### ISSUE TITLE
Create Footer Widgets

### ISSUE THREAD

**Issue by steventhomasmiller** [steventhomasmiller/National-School-of-Academic-Equitation#13]
These will contain the sitemap and client address.

**Comment by steventhomasmiller** [comment]
Hey @cbadger44, could you email me (so it's private) the login to the site's dashboard? I'm going to test out widget functionality.

**Comment by steventhomasmiller** [comment]
I'm having trouble getting the theme to appear on my local environment, and may need either @cbadger44's or Thomas' help next time we meet. I'm very new to this MAMP thing.

**Comment by cbadger44** [comment]
Horsey01   http://www.equitationstage.dreamhosters.com/wp-admin

Date: Thu, 16 Oct 2014 19:36:38 -0700

**Comment by cbadger44** [comment]
I can help you when we meet.

Date: Fri, 17 Oct 2014 14:33:55 -0700

**Comment by thomaswilburn** [comment]
Dammit Chris, that is not how you send a private e-mail. You should probably change that password now.

**Comment by steventhomasmiller** [comment]
I went ahead and changed it. The new password will be in our Google doc.

**Comment by cbadger44** [comment]
i got the footer figured out, im closing this and will push code tonight.
