### ISSUE TITLE
wordpress bare bones started

### ISSUE THREAD

**Issue by cbadger44** [steventhomasmiller/National-School-of-Academic-Equitation#2]
started the wordpress structure. it is still missing the nav bar though.

**Comment by cbadger44** [comment]
Have started the navigation. i will need to go into the wp dashboard and build sample posts/pages to test functionality.

**Comment by steventhomasmiller** [comment]
This looks done.

**Comment by steventhomasmiller** [comment]
On second thought, we'll probably continue to work on this one into the next sprint.

**Comment by cbadger44** [comment]
just some small functionality things that need to be addressed, like slider, sidebar areas

**Comment by steventhomasmiller** [comment]
I think we're beyond "bare bones" at this point, so I'll mark as resolved.
