### ISSUE TITLE
Create contact form

### ISSUE THREAD

**Issue by steventhomasmiller** [steventhomasmiller/National-School-of-Academic-Equitation#25]
We were going to use Contact Form 7, but instead will build our because we want more control over its design.

**Comment by steve-lexblog** [comment]
On second thought, I like Contact Form 7 quite a bit; it's easy to use and effective. Unless we can think of a better option, I will close this issue soon.

**Comment by steve-lexblog** [comment]
Whoops, forgot I was logged in to my work username. The same still stands.
